# Generated by Django 3.2.7 on 2021-10-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_horarioagenda_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(null=True, verbose_name='Dia da consulta')),
                ('horario', models.TimeField(null=True, verbose_name='Horário da consulta')),
                ('data_agendamento', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data do agendamento')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico', verbose_name='Médico da consulta')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
