# Generated by Django 3.2.7 on 2021-10-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_medico_crm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidademedica',
            options={'verbose_name': 'Especialidade', 'verbose_name_plural': 'Especialidades médicas'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.RemoveField(
            model_name='agendamedica',
            name='horarios',
        ),
        migrations.DeleteModel(
            name='HorarioAgenda',
        ),
    ]
