# Generated by Django 3.2.7 on 2021-10-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211001_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(verbose_name='Horário')),
            ],
        ),
        migrations.AddField(
            model_name='agendamedica',
            name='horarios',
            field=models.ManyToManyField(to='core.HorarioAgenda', verbose_name='Horários'),
        ),
    ]
