# Generated by Django 3.2.7 on 2021-10-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211001_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioagenda',
            options={'verbose_name': 'Horário', 'verbose_name_plural': 'Horários'},
        ),
    ]
