# Generated by Django 3.2.7 on 2021-10-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_horarioagenda_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamedica',
            name='horarios',
        ),
    ]
