# Generated by Django 3.2.7 on 2021-10-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agendamedica_horarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamedica',
            name='horarios',
        ),
        migrations.AddField(
            model_name='agendamedica',
            name='horarios',
            field=models.ManyToManyField(to='core.HorarioAgenda', verbose_name='Horários'),
        ),
    ]
